# Built using this context: /scripts/scrape_hashtags
FROM python:3.9-slim-buster

WORKDIR /app
COPY ./requirements_hashtagscrape.txt /app/requirements_hashtagscrape.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements_hashtagscrape.txt

COPY ./gethashtags.py /app/gethashtags.py


ENTRYPOINT ["python"]
CMD ["/app/gethashtags.py"]